name: DynMarket
main: io.github.kuohsuanlo.dynmarket.DynMarket
version: ${version}
loadbefore: [essentials]
commands:
  dsell:
    description: .
    aliases: ds
    usage:
  dbuy:
    description: .
    aliases: db
    usage: