ANCHOR_ITEM_ID: 264
DEFAULT_NUMBER_IN_MARKET: 100
SELLING_TAX_RATE: 0.07
BUYING_TAX_RATE: 0.03
YOU_SELL_ITEM_TEXT: '§a[DynMarket]§7 : You sold %id%:%data% * %sold_number% for total
  price : §6%total_price%§7. %item_left% left in stock.'
YOU_BUY_ITEM_TEXT: '§a[DynMarket]§7 : You bought %id%:%data% * %sold_number% for total
  price : §6%total_price%§7. %item_left% left in stock.'
NO_ITEM_LEFT: '§a[DynMarket]§7 : %id%:%data% * %item_left% left in stock.'
YOU_NOW_HAVE: '§a[DynMarket]§7 : You now have $%balance%.'
